pref("gamefox.elements.quickpost.form", true);
pref("gamefox.elements.quickpost.button", true);
pref("gamefox.elements.quickpost.link", true);
pref("gamefox.elements.quickpost.link.title", "QuickPost");
pref("gamefox.elements.tag.link", true);
pref("gamefox.elements.titlechange", true);
pref("gamefox.elements.titleprefix", true);
pref("gamefox.elements.msgnum", true);
pref("gamefox.elements.msgnum.style", 0);
pref("gamefox.elements.tracked.boardlink", true);

pref("gamefox.highlight.groups.1", "");
pref("gamefox.highlight.groups.2", "");
pref("gamefox.highlight.colors.1", "#CCFFFF");
pref("gamefox.highlight.colors.2", "#99CC66");
pref("gamefox.highlight.msgs", true);
pref("gamefox.highlight.topics", true);
pref("gamefox.highlight.ignore", false);
pref("gamefox.msgsPerPage", 50);
pref("gamefox.tpcsPerPage", 50);
pref("gamefox.msgSortOrder", 1);
pref("gamefox.tpcSortOrder", 4);
pref("gamefox.msgDisplay", 0);
pref("gamefox.timeZone", 0);

pref("gamefox.quote.header.italic", true);
pref("gamefox.quote.header.bold", true);
pref("gamefox.quote.header.date", false);
pref("gamefox.quote.header.username", true);
pref("gamefox.quote.header.messagenum", true);
pref("gamefox.quote.message.italic", true);
pref("gamefox.quote.message.bold", false);
pref("gamefox.quote.removesignature", true);
pref("gamefox.quote.style", "gfcode_full");
pref("gamefox.quote.style.custom", "<i><p><strong>Posted by %u</strong>\n%m</p></i>");

pref("gamefox.signature.serialized", "[{accounts:\"\", boards:\"\", body:\"\", presig:\"\"}]");
pref("gamefox.signature.newline", false);
pref("gamefox.signature.applyeverywhere", true);
pref("gamefox.signature.addition", 2);
pref("gamefox.signature.selection", 1);

pref("gamefox.theme.disablegamefaqscss", false);
pref("gamefox.theme.css.serialized", "({gamefox:{}, bundled:{}, user:{}})");

pref("gamefox.tags", "");
pref("gamefox.accounts", "");
pref("gamefox.topic.dblclick", 0);
pref("gamefox.message.dblclick", false);
pref("gamefox.message.header.dblclick", 0);
pref("gamefox.myposts.dblclick", 0);
pref("gamefox.paging.auto", false);
pref("gamefox.paging.location", 2);
pref("gamefox.paging.prefix", "[Pages: ");
pref("gamefox.paging.separator", ", ");
pref("gamefox.paging.suffix", "]");
pref("gamefox.context.accounts", true);
pref("gamefox.context.pagelist", true);
pref("gamefox.context.quote", true);
pref("gamefox.context.sidebar", true);
pref("gamefox.context.tag", true);
pref("gamefox.context.taglist", true);
pref("gamefox.context.tag.myposts", true);
pref("gamefox.context.tag.tracked", true);
pref("gamefox.options.page.selectedtab", 0);
